# Generated by Django 4.0.4 on 2023-04-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='todo',
            name='task',
            field=models.CharField(max_length=2000),
        ),
    ]
